---
jobs:
- name: fruit-basket-integration
  plan:
  - aggregate:
    - get: fruits
      trigger: true
  - task: integration-banana-test
    file: fruits/integration/banana-test.yml
  - task: integration-apple-test
    file: fruits/integration/apple-test.yml

resources:
- name: fruits
  type: git
  source:
    uri: https://github.com/degaurab/concourse101.git
    branch: master
